replicaCount: 2

aspnetEnvironment: Development

image:
  pullPolicy: Always

database:
  applyMigrations: "true"

logging:
  minimumLevel: Debug

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi