services:
  postgres:
    image: postgres:18
    container_name: api-bootcamp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: api_bootcamp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

    volumes:
      - api_bootcamp_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_bootcamp"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  seq:
    image: datalust/seq:latest
    container_name: api-bootcamp-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
    volumes:
      - api_bootcamp_seq_data:/data


  api-bootcamp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-bootcamp-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      APPLICATION_NAME: ApiBootcamp
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=api_bootcamp;Username=postgres;Password=${POSTGRES_PASSWORD}"
      Database__ApplyMigrations: "true"
      Seq__ServerUrl: "http://seq:80"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started

volumes:
  api_bootcamp_postgres_data: {}
  api_bootcamp_seq_data: {}