apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-bootcamp.labels" . | nindent 4 }}

type: Opaque

stringData:
  POSTGRES_PASSWORD: {{ required "postgres.password es obligatorio" .Values.postgres.password | quote }}

  ConnectionStrings__PostgreSQL: "Host={{ .Values.postgres.host }};Port={{ .Values.postgres.port }};Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ required "postgres.password es obligatorio" .Values.postgres.password }}"