{{- $postgresPassword := required "postgres.password es obligatorio" .Values.postgres.password -}}
{{- $seqPassword := required "seq.adminPassword es obligatorio" .Values.seq.adminPassword -}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-bootcamp.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ $postgresPassword | b64enc | quote }}
  ConnectionStrings__PostgreSQL: {{ printf "Host=%s;Port=%v;Database=%s;Username=%s;Password=%s" .Values.postgres.host .Values.postgres.port .Values.postgres.database .Values.postgres.username $postgresPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: seq-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-bootcamp.labels" . | nindent 4 }}
type: Opaque
data:
  SEQ_ADMIN_PASSWORD: {{ $seqPassword | b64enc | quote }}
