apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: api-bootcamp
type: Opaque
data:
  POSTGRES_DB: YXBpX2Jvb3RjYW1w
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: X19QT1NUR1JFU19QQVNTV09SRF9f