apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: api-bootcamp
type: Opaque
stringData:
  POSTGRES_DB: api_bootcamp
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "__POSTGRES_PASSWORD__"