apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-bootcamp.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-bootcamp.labels" . | nindent 4 }}

data:
  APPLICATION_NAME: {{ .Values.appName | quote }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.aspnetEnvironment | quote }}
  ASPNETCORE_HTTP_PORTS: {{ .Values.containerPort | quote }}
  Seq__ServerUrl: {{ .Values.seq.url | quote }}
  Database__ApplyMigrations: {{ .Values.database.applyMigrations | quote }}