apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-bootcamp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-bootcamp.labels" . | nindent 4 }}

type: Opaque
stringData:
  ConnectionStrings__PostgreSQL: "Host={{ .Values.postgres.host }};Port={{ .Values.postgres.port }};Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ required "postgres.password es obligatorio" .Values.postgres.password }}"